language: python
python:
matrix:
  include:

    # Full tests (with online API)
    - os: linux
      language: python
      python: 2.7
    - os: linux
      language: python
      python: 3.4
    - os: linux
      language: python
      python: 3.5
    - os: linux
      language: python
      python: 3.6
    - os: linux
      language: python
      python: 3.7
    - os: linux
      language: python
      python: 3.8
    - os: osx
      language: generic
      python: ">=3.6"

  fast_finish: true
  allow_failures:
    - python: 3.4

# command to install dependencies
install:
  - pip install -U pip
  - pip install codecov
  - pip install -U -r requirements.txt
  - pip install -U -r tests/requirements-dev.txt
  - python setup.py develop
# command to run tests
script:
  - pytest --cov=./
# uploading coverage report
after_success:
  - codecov
