language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -U pip
  - pip install codecov
  - pip install -U -r requirements.txt
  - python setup.py develop
# command to run tests
script:
  - pytest --cov=./
# uploading coverage report
after_success:
  - codecov
